"use strict";
exports.__esModule = true;
var express_1 = require("express");
var banner_controller_1 = require("../controllers/banner.controller");
var banner_middleware_1 = require("../middlewares/banner.middleware");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var bannerRoutes = (0, express_1.Router)();
bannerRoutes.get("/", banner_controller_1["default"].getAllBanner);
bannerRoutes.get("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, banner_controller_1["default"].getSingleBanner);
bannerRoutes.post("/", token_middleware_1["default"].verifyTokenAndAdmin, banner_middleware_1["default"].addNewBannerRules(), helpers_middleware_1["default"].entityValidator, banner_controller_1["default"].addNewBanner);
bannerRoutes["delete"]("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, banner_controller_1["default"].deleteBanner);
bannerRoutes.put("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, banner_middleware_1["default"].updateBannerRules(), helpers_middleware_1["default"].entityValidator, banner_controller_1["default"].updateBanner);
exports["default"] = bannerRoutes;
