"use strict";
exports.__esModule = true;
var express_1 = require("express");
var category_controller_1 = require("../controllers/category.controller");
var category_middleware_1 = require("../middlewares/category.middleware");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var categoryRoutes = (0, express_1.Router)();
categoryRoutes.get("/", category_controller_1["default"].getAllCategory);
categoryRoutes.get("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, category_controller_1["default"].getSingleCategory);
categoryRoutes.post("/", token_middleware_1["default"].verifyTokenAndAdmin, category_middleware_1["default"].addNewCategoryRules(), helpers_middleware_1["default"].entityValidator, category_controller_1["default"].addNewCategory);
categoryRoutes["delete"]("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, category_controller_1["default"].deleteCategory);
categoryRoutes.put("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, category_middleware_1["default"].updateCategoryRules(), helpers_middleware_1["default"].entityValidator, category_controller_1["default"].updateCategory);
exports["default"] = categoryRoutes;
