"use strict";
exports.__esModule = true;
var express_1 = require("express");
var auth_route_1 = require("./auth.route");
var banner_route_1 = require("./banner.route");
var category_route_1 = require("./category.route");
var product_route_1 = require("./product.route");
var cart_route_1 = require("./cart.route");
var order_route_1 = require("./order.route");
var user_route_1 = require("./user.route");
var shop_route_1 = require("./shop.route");
var voucher_route_1 = require("./voucher.route");
var wishlist_route_1 = require("./wishlist.route");
var review_route_1 = require("./review.route");
var import_route_1 = require("./import.route");
var response_1 = require("../utils/response");
var appRoutes = (0, express_1["default"])();
appRoutes.use("/api/import", import_route_1["default"]);
appRoutes.use("/api/auth", auth_route_1["default"]);
appRoutes.use("/api/category", category_route_1["default"]);
appRoutes.use("/api/product", product_route_1["default"]);
appRoutes.use("/api/banner", banner_route_1["default"]);
appRoutes.use("/api/cart", cart_route_1["default"]);
appRoutes.use("/api/order", order_route_1["default"]);
appRoutes.use("/api/user", user_route_1["default"]);
appRoutes.use("/api/shop", shop_route_1["default"]);
appRoutes.use("/api/voucher", voucher_route_1["default"]);
appRoutes.use("/api/wishlist", wishlist_route_1["default"]);
appRoutes.use("/api/review", review_route_1["default"]);
appRoutes.use(function (err, req, res, next) {
    (0, response_1.responseError)(err, res);
});
exports["default"] = appRoutes;
