"use strict";
exports.__esModule = true;
var express_1 = require("express");
var order_controller_1 = require("../controllers/order.controller");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var order_middleware_1 = require("../middlewares/order.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var orderRoutes = (0, express_1.Router)();
orderRoutes.post("/", token_middleware_1["default"].verifyToken, order_middleware_1["default"].createNewOrderRules(), helpers_middleware_1["default"].entityValidator, order_controller_1["default"].createNewOrder);
orderRoutes.get("/", token_middleware_1["default"].verifyTokenAndAdmin, order_controller_1["default"].getAllOrder);
orderRoutes.get("/me", token_middleware_1["default"].verifyToken, order_controller_1["default"].getAllOrderMe);
orderRoutes.get("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyToken, order_controller_1["default"].getSingleOrder);
orderRoutes["delete"]("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, order_controller_1["default"].deleteOrder);
orderRoutes.put("/:id/processing", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, order_controller_1["default"].updateStatusOrderToProcessing);
orderRoutes.put("/:id/shipping", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, order_controller_1["default"].updateStatusOrderToShipping);
orderRoutes.put("/:id/delivered", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, order_controller_1["default"].updateStatusOrderToDelivered);
orderRoutes.put("/:id/canceled", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyToken, order_controller_1["default"].updateStatusOrderToCancel);
exports["default"] = orderRoutes;
