"use strict";
exports.__esModule = true;
var express_1 = require("express");
var product_controller_1 = require("../controllers/product.controller");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var product_middleware_1 = require("../middlewares/product.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var productRoutes = (0, express_1.Router)();
productRoutes.get("/", product_middleware_1["default"].getProductsRules(), helpers_middleware_1["default"].entityValidator, product_controller_1["default"].getAllProduct);
productRoutes.get("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, product_controller_1["default"].getSingleProduct);
productRoutes.post("/", token_middleware_1["default"].verifyTokenAndAdmin, product_middleware_1["default"].addProductRules(), helpers_middleware_1["default"].entityValidator, product_controller_1["default"].addNewProduct);
productRoutes["delete"]("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, product_controller_1["default"].deleteProduct);
productRoutes.put("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyTokenAndAdmin, product_middleware_1["default"].updateProductRules(), helpers_middleware_1["default"].entityValidator, product_controller_1["default"].updateProduct);
exports["default"] = productRoutes;
