"use strict";
exports.__esModule = true;
var express_1 = require("express");
var review_controller_1 = require("../controllers/review.controller");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var review_middleware_1 = require("../middlewares/review.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var reviewRoutes = (0, express_1.Router)();
reviewRoutes.get("/product/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, review_controller_1["default"].getAllReviewProduct);
reviewRoutes.get("/order/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, review_controller_1["default"].getAllReviewOrder);
reviewRoutes.get("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, review_controller_1["default"].getSingleReview);
reviewRoutes.post("/", token_middleware_1["default"].verifyToken, review_middleware_1["default"].addNewReviewRules(), helpers_middleware_1["default"].entityValidator, review_controller_1["default"].addNewReview);
reviewRoutes["delete"]("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyToken, review_controller_1["default"].deleteReview);
reviewRoutes.put("/:id", helpers_middleware_1["default"].idRule("id"), helpers_middleware_1["default"].idValidator, token_middleware_1["default"].verifyToken, review_middleware_1["default"].updateReviewRules(), helpers_middleware_1["default"].entityValidator, review_controller_1["default"].updateReview);
exports["default"] = reviewRoutes;
