"use strict";
exports.__esModule = true;
var shop_controller_1 = require("../controllers/shop.controller");
var express_1 = require("express");
var token_middleware_1 = require("../middlewares/token.middleware");
var shop_middleware_1 = require("../middlewares/shop.middleware");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var shopRoutes = (0, express_1.Router)();
shopRoutes.get("/", shop_controller_1["default"].getShopInfo);
shopRoutes.get("/overview", token_middleware_1["default"].verifyTokenAndAdmin, shop_controller_1["default"].getOverviewDashboard);
shopRoutes.post("/", token_middleware_1["default"].verifyTokenAndAdmin, shop_middleware_1["default"].addShopInfoRules(), helpers_middleware_1["default"].entityValidator, shop_controller_1["default"].addShopInfo);
shopRoutes.put("/", token_middleware_1["default"].verifyTokenAndAdmin, shop_middleware_1["default"].updateShopInfoRules(), helpers_middleware_1["default"].entityValidator, shop_controller_1["default"].updateShopInfo);
shopRoutes["delete"]("/", token_middleware_1["default"].verifyTokenAndAdmin, shop_controller_1["default"].deleteShopInfo);
exports["default"] = shopRoutes;
