"use strict";
exports.__esModule = true;
var express_1 = require("express");
var wishlist_controller_1 = require("../controllers/wishlist.controller");
var helpers_middleware_1 = require("../middlewares/helpers.middleware");
var token_middleware_1 = require("../middlewares/token.middleware");
var wishlist_middleware_1 = require("../middlewares/wishlist.middleware");
var wishlistRoutes = (0, express_1.Router)();
wishlistRoutes.get("/", token_middleware_1["default"].verifyToken, wishlist_controller_1["default"].getMyWishlist);
wishlistRoutes.post("/", token_middleware_1["default"].verifyToken, wishlist_middleware_1["default"].addToWishlistRules(), helpers_middleware_1["default"].entityValidator, wishlist_controller_1["default"].addToWishlist);
wishlistRoutes["delete"]("/", token_middleware_1["default"].verifyToken, wishlist_middleware_1["default"].removeFromWishlist(), helpers_middleware_1["default"].entityValidator, wishlist_controller_1["default"].removeFromWishlist);
exports["default"] = wishlistRoutes;
